#!/bin/bash
# $1 project name

# Only run if project name is provided
if (( $# != 1 ))
then
  echo "Must provide project name"
  exit 1
fi

echo "--- Setting up remote repo ---"

# EDIT PATH TO PYTHON SCRIPT
# call python script
python3 /Path/to/create_git.py $1


# set up local branch
echo "--- Setting up local repo ---"

mkdir "$PWD/$1"
cd $1
git init .

#fetch username from github config file
name=`git config user.name`
#Currently a SSD link (can be replaced by https link)
git remote add origin git@github.com:$name/$1.git

# adding initial files
touch .gitignore
touch README.md

# pushing first commit
git add .
git commit -m "initialisation"
git push --set-upstream origin main

